sudo: required
services:
  - docker

before_install:
  - docker build -t debiasej/docker-react-learning -f Dockerfile.dev .

script:
  - docker run debiasej/docker-react-learning npm run test -- --coverage

